AWS_ACCESS_KEY_ID = 'AKIAIMXCTUTV3JDEWCCA'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'emeruchecole'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME


SECRET_KEY = '4zi(al-5lfb8zcc_tns+)@)xf7-6e-8*rw=_u*qe7tjd4%y)^i'
